version: '3.8'

services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=projetocarrinho

volumes:
  postgres_data: 